QUANTITY_FOOD_FOR_LAYING_EGG = 10
QUANTITY_ANT_FOR_LAYING_SOLDIER = 50
NEST_EXPANSION_RATE = 100
NEST_START_FOOD_STOCK = 50
NEST_START_CAPACITY = 15
MAX_SOLDIER_FOR_WORKER = 50 # 0...100 the max soldier per worker in %